_core:
  default_config_hash: t8e2t_Br0niDkKrqiSp51R2-jfyJF2BKfGIC0A35oZs
fields_extra: false
fields_extra_list: {  }
field_permissions: false
hidden_region: false
override_node_revision: false
override_node_revision_view_mode: full
switch_field: false
