_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 7821a5f5-f667-4a65-86bb-18dfd4d4d84a
name: 'Мій Богуслав'
mail: admin@example.com
slogan: 'Найрідніше місто в світі'
page:
  403: ''
  404: ''
  front: /node/21
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
